# Generated by Django 3.1.4 on 2020-12-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(help_text='Top left x box coordinate', verbose_name='x')),
                ('y', models.IntegerField(help_text='Top left x box coordinate', verbose_name='y')),
                ('width', models.IntegerField(help_text='width of the box', verbose_name='width')),
                ('height', models.IntegerField(help_text='height of the box', verbose_name='height')),
            ],
        ),
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='templates/')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.filetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('description', models.CharField(blank=True, help_text='Just to know for which template this location is', max_length=100, null=True, verbose_name='description')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.fieldcoordinate')),
                ('to_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.filetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='keyword')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webserver.location')),
            ],
        ),
    ]
