# Generated by Django 3.1.4 on 2021-01-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetemplate',
            name='company_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webserver.company'),
            preserve_default=False,
        ),
    ]
