from .list_template_view import ListTemplateView
from .upload_file_view import UploadFileView
from .download_file_view import DownloadFileView
from .download_file_csv_view import DownloadFileCsvView
from .download_file_json_view import DownloadFileJsonView
from .choise_of_result_view import ChoiseOfResultView
